export const Colors = {
  background: "#f8fafc",
  foreground: "#0f172a",
  sidebarBg: "#1e293b",
  cardBg: "#ffffff",
  cardBorder: "#e2e8f0",
  accent: "#3b82f6",
  accentHover: "#2563eb",
  success: "#22c55e",
  danger: "#ef4444",
  warning: "#f59e0b",
  purple: "#8b5cf6",
  slate100: "#f1f5f9",
  slate200: "#e2e8f0",
  slate300: "#cbd5e1",
  slate400: "#94a3b8",
  slate500: "#64748b",
  slate600: "#475569",
  white: "#ffffff",
};

export const bankColors: Record<string, string> = {
  BancoEstado: "#00529B",
  BancoChile: "#D52B1E",
  Santander: "#EC0000",
  BCI: "#F37920",
  "Itaú": "#FF6600",
  Scotiabank: "#EC1C24",
  BancoFalabella: "#8BC53F",
  BancoRipley: "#6D2077",
  BICE: "#003DA5",
  Security: "#00447C",
  Otro: "#6B7280",
};

export const categoryEmojis: Record<string, string> = {
  alimentacion: "🍔",
  transporte: "🚗",
  vivienda: "🏠",
  salud: "🏥",
  educacion: "📚",
  entretenimiento: "🎬",
  ropa: "👕",
  servicios: "💡",
  transferencia: "🔄",
  sueldo: "💰",
  freelance: "💻",
  inversiones: "📈",
  otros: "📋",
};

export const categoryLabels: Record<string, string> = {
  alimentacion: "Alimentación",
  transporte: "Transporte",
  vivienda: "Vivienda",
  salud: "Salud",
  educacion: "Educación",
  entretenimiento: "Entretenimiento",
  ropa: "Ropa",
  servicios: "Servicios",
  transferencia: "Transferencia",
  sueldo: "Sueldo",
  freelance: "Freelance",
  inversiones: "Inversiones",
  otros: "Otros",
};
